version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hiremind_postgres
    environment:
      POSTGRES_DB: hiremind_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hiremind_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hiremind_backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hiremind_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - JWT_SECRET_KEY=supersecret
      - FRONTEND_URL=${FRONTEND_URL:-http://16.171.129.143}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - backend_uploads:/app/backend/uploads
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: hiremind_frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_uploads:
