"""add interview events

Revision ID: 000b4a4b5a34
Revises: 6bcfe4536725
Create Date: 2026-07-21 18:00:45.279835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000b4a4b5a34'
down_revision: Union[str, Sequence[str], None] = '6bcfe4536725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_events', 'details',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('interviews', 'final_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('final_report', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('interview_events', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
