"""create candidate applications table

Revision ID: 1e2bc3143a62
Revises: b0fef2d4ea5a
Create Date: 2026-07-13 18:23:56.346750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2bc3143a62'
down_revision: Union[str, Sequence[str], None] = 'b0fef2d4ea5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('resume_filename', sa.String(length=500), nullable=True),
    sa.Column('resume_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEW_SENT', 'INTERVIEW_COMPLETED', 'SELECTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('resume_score', sa.Float(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('is_shortlisted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_applications_email'), 'candidate_applications', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_applications_email'), table_name='candidate_applications')
    op.drop_table('candidate_applications')
    # ### end Alembic commands ###
