"""add ai screening fields

Revision ID: 559277123fe3
Revises: 1e2bc3143a62
Create Date: 2026-07-15 14:55:53.670119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559277123fe3'
down_revision: Union[str, Sequence[str], None] = '1e2bc3143a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_applications', sa.Column('parsed_resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_applications', 'parsed_resume_text')
    # ### end Alembic commands ###
