"""add interview fields

Revision ID: 8b7e1a9b712e
Revises: 25a8367297f7
Create Date: 2026-07-17 14:53:05.694001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7e1a9b712e'
down_revision: Union[str, Sequence[str], None] = '25a8367297f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_applications', sa.Column('ai_feedback', sa.Text(), nullable=True))
    op.add_column(
    'candidate_applications',
    sa.Column(
        'screening_completed',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    op.add_column('candidate_applications', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.add_column('candidate_applications', sa.Column('interview_link', sa.String(length=500), nullable=True))
    op.add_column('candidate_applications', sa.Column('interviewer_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_applications', 'interviewer_name')
    op.drop_column('candidate_applications', 'interview_link')
    op.drop_column('candidate_applications', 'interview_date')
    op.drop_column('candidate_applications', 'screening_completed')
    op.drop_column('candidate_applications', 'ai_feedback')
    # ### end Alembic commands ###
